services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/util:/app/util 
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4200:4200"

